name: Node.js CI

on:
  push:
    branches: [ main, Andrews_Branch ]
  pull_request:
    branches: [ main, Andrews_Branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: main-src
    - name: Run tests
      run: npm run test -- --runInBand
      working-directory: main-src
