name: Node.js CI

on:
  push:
    branches: [ Andrews_Branch ]
  pull_request:
    branches: [ Andrews_Branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: npm i
      working-directory: main-src
    - name: Run tests
      run: npm run test --runInBand
      working-directory: main-src